name: Build and Upload to Nexus

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Get short Git hash
        id: get-git-hash
        run: |
          GIT_HASH=$(git rev-parse --short HEAD)
          echo "GIT_HASH=$GIT_HASH" >> $GITHUB_ENV

      - name: Build project
        run: ./gradlew build

      - name: Find base JAR file
        id: find-jar
        run: |
          echo "Looking in build/libs/"
          JAR_FILES=(build/libs/ParadiseClient-*.jar)
          BASE_JAR_FILES=()
          for file in "${JAR_FILES[@]}"; do
            if [[ ! "$file" == *"-dev.jar" && ! "$file" == *"-sources.jar" ]]; then
              BASE_JAR_FILES+=("$file")
            fi
          done
          if [ ${#BASE_JAR_FILES[@]} -ne 1 ]; then
            echo "Error: Expected exactly one base JAR, found ${#BASE_JAR_FILES[@]}"
            exit 1
          fi
          JAR_FILE="${BASE_JAR_FILES[0]}"
          echo "Found JAR file: $JAR_FILE"
          echo "JAR_FILE=$JAR_FILE" >> $GITHUB_ENV
          echo "JAR_NAME=$(basename "$JAR_FILE")" >> $GITHUB_ENV

      - name: Upload JAR to Nexus
        run: |
          echo "Uploading ${{ env.JAR_FILE }} to Nexus..."
          curl -v -X PUT "https://paradise-client.net/api/versions" \
               -u "${{ secrets.NEXUS_USERNAME }}:${{ secrets.NEXUS_PASSWORD }}" \
               -H "Content-Type: application/java-archive" \
               --data-binary @"${{ env.JAR_FILE }}"

      # Optional: Upload to GitHub for visibility
      - name: Upload artifact to GitHub (optional)
        uses: actions/upload-artifact@v4
        with:
          name: ParadiseClient
          path: ${{ env.JAR_FILE }}
